Repository GSG-FC03/Cinema_App-Team_1, pull requests merged in 2021-06, with the labels that each got.

#7 File Structure
  CSS-Folder/Download.css
  CSS-Folder/Home.css
  CSS-Folder/Movie_Info.css
Labels: To-Be-Reviewed

#9 I added html files and Images
  HTML/Download.html
  HTML/Home.html
  HTML/Movie_info.html
  Images/image-12.png
  Images/image-37.png
Labels: To-Be-Reviewed

#17 4 create a home page
  CSS-Folder/Home.css
  HTML/Home.html
Labels: Done

#19 Modify Structure- delete unnecessary Files in structure
  Actor-Font/Actor-Regular.ttf
  Actor-Font/OFL.txt
  Image-Folder/Images.html
Labels: To-Be-Reviewed

#8 Initial readme file
  README.md
Labels: Done

#20 5 create movie info
  CSS-Folder/Movie_Info.css
  HTML/Movie_info.html
Labels: Done

#24 Home Page: Add Linking to download page and description/ Movie Info Page
  CSS-Folder/Home.css
  HTML/Home.html
Labels: Done, To-Be-Reviewed

#27 Modify MovieInfo
  CSS-Folder/Movie_Info.css
  HTML/Movie_info.html
Labels: To-Be-Reviewed

#26 Finalizing Readme File
  README.md
Labels: under-work

#21 6- Create Download Page
  CSS-Folder/Download.css
  HTML/Download.html
Labels: To-Be-Reviewed
